sonar.projectKey=com.natsmonitor:nats-monitoring
sonar.projectName=NATS Monitoring Application
sonar.projectVersion=1.0.0-SNAPSHOT

sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java,src/main/resources
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.coverage.exclusions=src/main/java/com/natsmonitor/config/**,src/main/java/com/natsmonitor/dto/**,src/main/java/com/natsmonitor/model/**,src/main/java/com/natsmonitor/NatsMonitoringApplication.java
