{{- if .Values.smtp.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nats-monitor.fullname" . }}-smtp
  labels:
    {{- include "nats-monitor.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.smtp.username | b64enc | quote }}
  password: {{ .Values.smtp.password | b64enc | quote }}
{{- end }}
{{- if and .Values.smtp.username .Values.nats.username }}
---
{{- end }}
{{- if .Values.nats.username }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nats-monitor.fullname" . }}-nats
  labels:
    {{- include "nats-monitor.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.nats.username | b64enc | quote }}
  password: {{ .Values.nats.password | b64enc | quote }}
{{- end }}
{{- if or .Values.nats.tls.keyStorePassword .Values.nats.tls.keyPassword .Values.nats.tls.trustStorePassword }}
{{- if or .Values.smtp.username .Values.nats.username }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nats-monitor.fullname" . }}-nats-tls
  labels:
    {{- include "nats-monitor.labels" . | nindent 4 }}
type: Opaque
data:
  key-store-password: {{ .Values.nats.tls.keyStorePassword | b64enc | quote }}
  key-password: {{ .Values.nats.tls.keyPassword | b64enc | quote }}
  trust-store-password: {{ .Values.nats.tls.trustStorePassword | b64enc | quote }}
{{- end }}
