CREATE TABLE IF NOT EXISTS alert_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(64) NOT NULL,
    stream_name VARCHAR(255),
    consumer_name VARCHAR(255),
    threshold BIGINT NOT NULL,
    severity VARCHAR(32) NOT NULL DEFAULT 'WARNING',
    email_recipient VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    email_enabled BOOLEAN NOT NULL,
    webhook_url VARCHAR(2048),
    webhook_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    last_triggered TIMESTAMP,
    last_notified TIMESTAMP,
    cooldown_minutes INT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS alert_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_name VARCHAR(255) NOT NULL,
    alert_type VARCHAR(64) NOT NULL,
    message VARCHAR(2048) NOT NULL,
    stream_name VARCHAR(255),
    consumer_name VARCHAR(255),
    current_value BIGINT NOT NULL,
    threshold BIGINT NOT NULL,
    severity VARCHAR(32) NOT NULL DEFAULT 'WARNING',
    resolved BOOLEAN NOT NULL DEFAULT FALSE,
    email_sent_to VARCHAR(255) NOT NULL,
    email_sent BOOLEAN NOT NULL,
    webhook_url VARCHAR(2048),
    webhook_sent BOOLEAN NOT NULL DEFAULT FALSE,
    error_message VARCHAR(255),
    triggered_at TIMESTAMP NOT NULL
);

ALTER TABLE alert_rules ADD COLUMN IF NOT EXISTS severity VARCHAR(32) NOT NULL DEFAULT 'WARNING';
ALTER TABLE alert_history ADD COLUMN IF NOT EXISTS severity VARCHAR(32) NOT NULL DEFAULT 'WARNING';
ALTER TABLE alert_history ADD COLUMN IF NOT EXISTS resolved BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE alert_history ALTER COLUMN message VARCHAR(2048);

CREATE TABLE IF NOT EXISTS nats_metric_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    captured_at TIMESTAMP NOT NULL,
    server_id VARCHAR(255),
    server_name VARCHAR(255),
    uptime VARCHAR(255),
    memory_bytes BIGINT NOT NULL,
    cpu DOUBLE NOT NULL,
    connections INT NOT NULL,
    total_connections BIGINT NOT NULL,
    subscriptions BIGINT NOT NULL,
    slow_consumers BIGINT NOT NULL,
    in_msgs BIGINT NOT NULL,
    out_msgs BIGINT NOT NULL,
    in_bytes BIGINT NOT NULL,
    out_bytes BIGINT NOT NULL,
    routes INT NOT NULL,
    leafnodes INT NOT NULL,
    streams INT NOT NULL,
    consumers INT NOT NULL
);

CREATE TABLE IF NOT EXISTS nats_consumer_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    captured_at TIMESTAMP NOT NULL,
    stream_name VARCHAR(255),
    consumer_name VARCHAR(255),
    durable_name VARCHAR(255),
    filter_subject VARCHAR(1024),
    lag BIGINT NOT NULL,
    pending_messages BIGINT NOT NULL,
    ack_pending BIGINT NOT NULL,
    redelivered BIGINT NOT NULL,
    waiting BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS nats_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    received_at TIMESTAMP NOT NULL,
    subject VARCHAR(1024) NOT NULL,
    category VARCHAR(64) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    server_id VARCHAR(255),
    account_id VARCHAR(255),
    resource VARCHAR(1024),
    summary VARCHAR(2048),
    payload CLOB
);

CREATE TABLE IF NOT EXISTS incidents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    type VARCHAR(255) NOT NULL,
    resource VARCHAR(1024) NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary VARCHAR(2048),
    first_seen TIMESTAMP NOT NULL,
    last_seen TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    event_count BIGINT NOT NULL,
    last_event_type VARCHAR(1024),
    last_message VARCHAR(2048)
);

CREATE INDEX IF NOT EXISTS idx_alert_history_triggered_at ON alert_history(triggered_at);
CREATE INDEX IF NOT EXISTS idx_metric_snapshots_captured_at ON nats_metric_snapshots(captured_at);
CREATE INDEX IF NOT EXISTS idx_consumer_snapshots_captured_at ON nats_consumer_snapshots(captured_at);
CREATE INDEX IF NOT EXISTS idx_nats_events_received_at ON nats_events(received_at);
CREATE INDEX IF NOT EXISTS idx_incidents_status_last_seen ON incidents(status, last_seen);
