ALTER TABLE alert_rules ADD COLUMN IF NOT EXISTS consumer_name VARCHAR(255);
ALTER TABLE alert_rules ADD COLUMN IF NOT EXISTS severity VARCHAR(32) NOT NULL DEFAULT 'WARNING';
ALTER TABLE alert_rules ADD COLUMN IF NOT EXISTS email_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE alert_rules ADD COLUMN IF NOT EXISTS webhook_url VARCHAR(2048);
ALTER TABLE alert_rules ADD COLUMN IF NOT EXISTS webhook_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE alert_history ADD COLUMN IF NOT EXISTS severity VARCHAR(32) NOT NULL DEFAULT 'WARNING';
ALTER TABLE alert_history ADD COLUMN IF NOT EXISTS resolved BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE alert_history ADD COLUMN IF NOT EXISTS webhook_url VARCHAR(2048);
ALTER TABLE alert_history ADD COLUMN IF NOT EXISTS webhook_sent BOOLEAN NOT NULL DEFAULT FALSE;
